# requirements.yaml
dependencies:
  - alias: blockchain-prod-1
    name: blockchain
    version: "0.1.0"
    repository: file://../blockchain
    tags:
      - blockchain
      - master
  - alias: blockchain-prod-2
    name: blockchain
    version: "0.1.0"
    repository: file://../blockchain
    tags:
      - blockchainSecond
      - master
  - alias: blockchain-test-1
    name: blockchain
    version: "0.1.0"
    repository: file://../blockchain
    tags:
      - blockchain
      - master
  - alias: blockchain-test-2
    name: blockchain
    version: "0.1.0"
    repository: file://../blockchain
    tags:
      - blockchainSecond
      - master
  - alias: api-prod-1
    name: api
    version: "0.1.0"
    repository: file://../api
    tags:
      - api
      - master
  - alias: api-prod-2
    name: api
    version: "0.1.0"
    repository: file://../api
    tags:
      - apiSecond
      - master
  - alias: api-test-1
    name: api
    version: "0.1.0"
    repository: file://../api
    tags:
      - api
      - master
  - alias: api-test-2
    name: api
    version: "0.1.0"
    repository: file://../api
    tags:
      - apiSecond
      - master
  - alias: frontend-1
    name: frontend
    version: "0.1.0"
    repository: file://../frontend
    tags:
      - frontend
      - master
  - alias: frontend-2
    name: frontend
    version: "0.1.0"
    repository: file://../frontend
    tags:
      - frontendSecond
      - master
