# Number of labels to fetch (optional). Defaults to 100
numLabels: 40
# These labels will not be used even if the issue contains them (optional).
# Pass a blank array if no labels are to be excluded.
# excludeLabels: []
excludeLabels:
  - "duplicate"
  # - pinned
# custom configuration to override default behaviour
# control explicitly what gets added and when
custom:
  - location: body
    keywords:
      - "blockchain"
    labels:
      - blockchain
  - location: body
    keywords:
      - "api"
    labels:
      - api
  - location: body
    keywords:
      - "frontend"
    labels:
      - frontend
  - location: body
    keywords:
      - "storage-service"
    labels:
      - storage-service
  - location: body
    keywords:
      - "excel-export-service"
      - "export-service"
    labels:
      - excel-export-service
  - location: body
    keywords:
      - "email-notification-service"
      - "email-service"
    labels:
      - email-notification-service
