version: "3.2"
services:
  master:
    image: trubudget/blockchain:latest
    environment:
      RPC_PORT: ${RPC_PORT}
      ORGANIZATION: ${ORGANIZATION}
      RPC_PASSWORD: ${RPC_PASSWORD}
      EXTERNAL_IP: ${EXTERNAL_IP}
    volumes:
      - /tmp/bcMasterVolume:/root/.multichain
    ports:
      - "7447:7447"
      - "8000:8000"
  api:
    image: trubudget/api:latest
    environment:
      RPC_HOST: ${RPC_HOST}
      RPC_PORT: ${RPC_PORT}
      ROOT_SECRET: ${ROOT_SECRET}
      RPC_PASSWORD: ${RPC_PASSWORD}
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
    links:
      - master
    ports:
      - "8080:8080"
  provisioning:
    image: trubudget/provisioning:latest
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      ENVIRONMENT_TYPE: ${ENVIRONMENT_TYPE}
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
    links:
      - api
