version: "3.2"
services:
  api:
    build:
      context: ../../api
    environment:
      RPC_HOST: master
      RPC_PORT: ${RPC_PORT}
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      ROOT_SECRET: ${ROOT_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
      SWAGGER_BASEPATH: /prod
    links:
      - master
    ports:
      - "8080:${API_PORT}"

  master:
    build:
      context: ../../blockchain
    environment:
      RPC_PORT: ${RPC_PORT}
      ORGANIZATION: ${ORGANIZATION}
      EXTERNAL_IP: ${EXTERNAL_IP}
    volumes:
      - /tmp/bcMasterVolume:/root/.multichain

  testapi:
    build:
      context: ../../api
    environment:
      RPC_HOST: testmaster
      RPC_PORT: ${RPC_PORT}
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      ROOT_SECRET: ${ROOT_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
      SWAGGER_BASEPATH: /test
    links:
      - testmaster
    ports:
      - "8081:${API_PORT}"

  testmaster:
    build:
      context: ../../blockchain
    environment:
      RPC_PORT: ${RPC_PORT}
      ORGANIZATION: ${ORGANIZATION}
      EXTERNAL_IP: ${EXTERNAL_IP}
    volumes:
      - /tmp/bcTestMasterVolume:/root/.multichain

  frontend:
    build:
      context: ../../frontend
    environment:
      PROD_API_HOST: api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: testapi
      TEST_API_PORT: ${API_PORT}
    links:
      - api
      - testapi
    ports:
      - "80:80"
