version: '3.2'
services:
  api:
    image: index.docker.io/trubudget/v1/api:${TAG}
    ports:
      - "8088:8080" # Mapping the nginx port 
    environment:
      RPC_HOST: master
      RPC_PORT: ${RPC_PORT}
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      ROOT_SECRET: ${ROOT_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
      SWAGGER_BASEPATH: /prod
      # for real deployment comment the BC_ADDRESS_VERIFACTION, otherwise everyone can create transaction from anywhere
    links: 
      - master

  master:
    image: index.docker.io/trubudget/v1/blockchain:${TAG}
    environment:
      RPC_PORT: ${RPC_PORT}
      ORGANIZATION: ${ORGANIZATION}
#     EXTERNAL_IP: ${EXTERNAL_IP}
    volumes:
      - /tmp/bcMasterVolume:/root/.multichain

  testapi:
    image: index.docker.io/trubudget/v1/api:${TAG}
    ports:
      - "8089:8080" # Mapping the nginx port 
    environment:
      RPC_HOST: testmaster
      RPC_PORT: ${RPC_PORT}
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      ROOT_SECRET: ${ROOT_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
      SWAGGER_BASEPATH: /test
    links: 
      - testmaster

  testmaster:
    image: index.docker.io/trubudget/v1/blockchain:${TAG}
    environment:
      RPC_PORT: ${RPC_PORT}
      ORGANIZATION: ${ORGANIZATION}
#      EXTERNAL_IP: ${EXTERNAL_IP}
    volumes:
      - /tmp/bcTestMasterVolume:/root/.multichain

  frontend:
    image: index.docker.io/trubudget/v1/frontend:${TAG}
    ports:
      - "80:80" # Mapping the nginx port 
    environment:
      PROD_API_HOST: api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: testapi
      TEST_API_PORT: ${API_PORT}
    links:
      - api
      - testapi

  provision-prod:
    image: index.docker.io/trubudget/v1/provisioning:${TAG}
    command: ["npm", "start"]
    environment:
      API_HOST: api
      API_PORT: 8080
      ENVIRONMENT_TYPE: PROD
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
    links: 
      - api

  provision-test:
    image: index.docker.io/trubudget/v1/provisioning:${TAG}
    command: ["npm", "start"]
    environment:
      API_HOST: testapi
      API_PORT: 8080
      ENVIRONMENT_TYPE: PROD
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
    links: 
      - testapi
  
