version: '3.2'
services:
  api:
    image: index.docker.io/trubudget/v1/api:${TAG}
    environment:
      RPC_HOST: bc-slave
      RPC_PORT: ${RPC_PORT}
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      ROOT_SECRET: ${ROOT_SECRET}
      RPC_PASSWORD: s750SiJnj50yIrmwxPnEdSzpfGlTAHzhaUwgqKeb0G1j
      # for real deployment comment the BC_ADDRESS_VERIFACTION, otherwise everyone can create transaction from anywhere
    links: 
      - bc-slave

  bc-slave:
    image: index.docker.io/trubudget/v1/blockchain:${TAG}
    environment:
      CHAINNAME: ${CHAINNAME}
      RPC_PORT: ${RPC_PORT}
      ORGANIZATION: ${ORGANIZATION}
      RPC_PASSWORD: s750SiJnj50yIrmwxPnEdSzpfGlTAHzhaUwgqKeb0G1j
      P2P_HOST: ${P2P_PROD_HOST}
      P2P_PORT: ${P2P_PROD_PORT}
      API_PROTO: http
      API_HOST: ${API_PROD_HOST}
      API_PORT: ${API_PROD_PORT}
    volumes:
      - /tmp/bcSlaveVolume:/root/.multichain

  testapi:
    image: index.docker.io/trubudget/v1/api:${TAG}
    environment:
      RPC_HOST: test-bc-slave
      RPC_PORT: ${RPC_PORT}
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      ROOT_SECRET: ${ROOT_SECRET}
      RPC_PASSWORD: s750SiJnj50yIrmwxPnEdSzpfGlTAHzhaUwgqKeb0G1j
      # for real deployment comment the BC_ADDRESS_VERIFACTION, otherwise everyone can create transaction from anywhere
    links: 
      - test-bc-slave

  test-bc-slave:
    image: index.docker.io/trubudget/v1/blockchain:${TAG}
    environment:
      CHAINNAME: ${CHAINNAME}
      RPC_PORT: ${RPC_PORT}
      ORGANIZATION: ${ORGANIZATION}
      RPC_PASSWORD: s750SiJnj50yIrmwxPnEdSzpfGlTAHzhaUwgqKeb0G1j
      P2P_HOST: ${P2P_TEST_HOST}
      P2P_PORT: ${P2P_TEST_PORT}
      API_PROTO: http
      API_HOST: ${API_TEST_HOST}
      API_PORT: ${API_TEST_PORT}
    volumes:
      - /tmp/bcTestSlaveVolume:/root/.multichain



  frontend:
    image: index.docker.io/trubudget/v1/frontend:${TAG}
    ports:
      - "80:80" # Mapping the nginx port 
    environment:
      PROD_API_HOST: api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: testapi
      TEST_API_PORT: ${API_PORT}
    links:
      - api
      - testapi

