name: "Audit"
runs:
  using: "composite"
  steps:
    - name: Audit project ${{ matrix.project }}
      run: cd ${{ matrix.project }} && npm install --no-audit && npm run audit -- --production
      shell: bash
