version: "3"
services:
  master-node:
    build: ../../blockchain
    environment:
      RPC_HOST: master-node
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
    ports:
      - ${RPC_PORT}:${RPC_PORT}
      - "8085:8085"
      - "7447:7447"

  master-api:
    build: ../../api
    environment:
      APP_NAME: Trubudget
      PORT: ${API_PORT}
      NODE_LOCATION_LAT: "30.11"
      NODE_LOCATION_LNG: "4.68"
      NODE_COUNTRY: Brasil
      NODE_DESCRIPTION: UmbrellaCorp
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      RPC_HOST: master-node
      RPC_PORT: ${RPC_PORT}
      ROOT_SECRET: ${ROOT_SECRET}
      RPC_PASSWORD: ${RPC_PASSWORD}
      MINIO_ENDPOINT: nginx
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: ["npm", "run", "dev"]
    volumes:
      - "../../api/src:/home/node/src:delegated"
    links:
      - minio1
      - nginx
    ports:
      - ${API_PORT}:${API_PORT}
      - "9230:9229"
    depends_on:
      - master-node

  provisioning:
    build:
      context: ../../provisioning
    command: ["npm", "start"]
    environment:
      API_HOST: master-api
      API_PORT: ${API_PORT}
      ENVIRONMENT_TYPE: PROD
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
    depends_on:
      - master-api

  excel-export:
    build: ../../excel-export
    environment:
      PROD_API_HOST: master-api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: master-api
      TEST_API_PORT: ${API_PORT}
      PORT: 8888
    command: ["npm", "run", "dev"]
    volumes:
      - "../../excel-export/src:/home/node/src:delegated"
    ports:
      - "8888:8888"
      - "9231:9229"
    depends_on:
      - master-api

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.dev
      args:
        API_HOST: master-api
        API_PORT: ${API_PORT}
    environment:
      PORT: 3000
      NODE_ENV: ${NODE_ENV}
      CHOKIDAR_USEPOLLING: "true" # for hot reloading of source files
      REACT_APP_VERSION: ${REACT_APP_VERSION}
      REACT_APP_EXPORT_SERVICE_ENABLED: "true"
    volumes:
      - "../../frontend/src:/app/src"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - master-api
      - excel-export
    stdin_open: true

  minio1:
    image: minio/minio
    volumes:
      - ../../minio/data:/data
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ../../minio/nginx:/etc/nginx:ro
    ports:
      - "9000:9000"
    depends_on:
      - minio1

  bc-slave:
    image: trubudget/blockchain:${TAG}
    environment:
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: "Orga1"
      P2P_HOST: master-node
      P2P_PORT: ${P2P_PROD_PORT}
      API_PROTO: http
      API_HOST: master-api
      API_PORT: ${API_PORT}
      EXTERNAL_IP: master-node
    links:
      - master-node
      - master-api
    ports:
      - "7448:7447"

  bc-slave2:
    image: trubudget/blockchain:${TAG}
    environment:
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: "Orga2"
      P2P_HOST: master-node
      P2P_PORT: ${P2P_PROD_PORT}
      API_PROTO: http
      API_HOST: master-api
      API_PORT: ${API_PORT}
      EXTERNAL_IP: master-node
    links:
      - master-node
      - master-api
    ports:
      - "7449:7447"

  bc-slave3:
    image: trubudget/blockchain:${TAG}
    environment:
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: "Orga3"
      P2P_HOST: master-node
      P2P_PORT: ${P2P_PROD_PORT}
      API_PROTO: http
      API_HOST: master-api
      API_PORT: ${API_PORT}
      EXTERNAL_IP: master-node
    links:
      - master-node
      - master-api
    ports:
      - "7450:7447"

  bc-slave4:
    image: trubudget/blockchain:${TAG}
    environment:
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: "Orga4"
      P2P_HOST: master-node
      P2P_PORT: ${P2P_PROD_PORT}
      API_PROTO: http
      API_HOST: master-api
      API_PORT: ${API_PORT}
      EXTERNAL_IP: master-node
    links:
      - master-node
      - master-api
    ports:
      - "7451:7447"

  bc-slave5:
    image: trubudget/blockchain:${TAG}
    environment:
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: "Orga5"
      P2P_HOST: master-node
      P2P_PORT: ${P2P_PROD_PORT}
      API_PROTO: http
      API_HOST: master-api
      API_PORT: ${API_PORT}
      EXTERNAL_IP: master-node
    links:
      - master-node
      - master-api
    ports:
      - "7452:7447"

  bc-slave6:
    image: trubudget/blockchain:${TAG}
    environment:
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: Orga6
      P2P_HOST: master-node
      P2P_PORT: ${P2P_PROD_PORT}
      API_PROTO: http
      API_HOST: master-api
      API_PORT: ${API_PORT}
      EXTERNAL_IP: master-node
    links:
      - master-node
      - master-api
    ports:
      - "7453:7447"
