version: "3.2"
services:
  master-api:
    build:
      context: ../../api
    environment:
      RPC_HOST: master-chain
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      ROOT_SECRET: ${ROOT_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
    links:
      - master-chain
    volumes:
      - ../../api/src:/home/node/src
      - ../../api/dist:/home/node/dist
    command: ["npm", "run", "watch"]
    ports:
      - 8000:${API_PORT}
      - "8085:8085"

  master-chain:
    # image: trubudget/blockchain:latest
    build:
      context: ../../blockchain
    environment:
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
      EXTERNAL_IP: ${EXTERNAL_IP}
    command: ["npm", "run", "watch"]
    volumes:
      - ../../blockchain/src:/home/node/src
    #   - /tmp/bcMasterVolume:/root/.multichain
    ports:
      - "7447:7447"

  # frontend cannot be hot-loaded, container contains only built application, no source files
  master-frontend:
    image: trubudget/frontend:latest
    environment:
      PROD_API_HOST: master-api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: master-api
      TEST_API_PORT: ${API_PORT}
      # EXPORT_HOST: export
      # EXPORT_PORT: 8888
    depends_on:
      - master-api
    ports:
      - "80:80"

  provisioning:
    build:
      context: ../../provisioning
    command: ["npm", "run", "wait"]
    environment:
      API_HOST: master-api
      API_PORT: ${API_PORT}
      ENVIRONMENT_TYPE: PROD
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
    volumes:
      - "../../provisioning/src:/usr/src/app/src:delegated"
    depends_on:
      - master-api

  slave-api:
    build:
      context: ../../api
    environment:
      RPC_HOST: slave-chain
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      ROOT_SECRET: ${ROOT_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
    command: ["npm", "run", "watch"]
    ports:
      - 8001:${API_PORT}
      - "8086:8085"

  slave-chain:
    # image: trubudget/blockchain:latest
    build:
      context: ../../blockchain
    environment:
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
      P2P_HOST: master-chain
      P2P_PORT: 7447
      API_PROTO: http
      API_HOST: slave-api
      API_PORT: ${API_PORT}
      MASTER_API_HOST: master-api
      MASTER_API_PORT: ${API_PORT}
    depends_on:
      - master-chain
    links:
      - slave-api
      - master-api
    ports:
      - "7448:7447" # SLAVE_P2P_PORT

  slave-frontend:
    image: trubudget/frontend:latest
    environment:
      PROD_API_HOST: slave-api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: slave-api
      TEST_API_PORT: ${API_PORT}
      # EXPORT_HOST: export
      # EXPORT_PORT: 8888
    depends_on:
      - slave-api
    ports:
      - "81:80"
      - "3001:3000"
