version: "3"
services:
  master-node:
    image: trubudget/blockchain:${TAG}
    environment:
      RPC_HOST: master-node
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      LOG_LEVEL: ${BLOCKCHAIN_LOG_LEVEL}
    # volume for persisting data from multichain
    volumes:
      - /masterVolume:/root/.multichain
    ports:
      - ${RPC_PORT}:${RPC_PORT}
      - "8085:8085"
      - "7447:7447"

  emaildb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      # volume for persisting data
    volumes:
      - /emaildbVolume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    # volume for persisting data
    volumes:
      - /minioVolume:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  master-api:
    image: trubudget/api:${TAG}
    environment:
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      RPC_HOST: master-node
      RPC_PORT: ${RPC_PORT}
      ROOT_SECRET: ${ROOT_SECRET}
      RPC_PASSWORD: ${RPC_PASSWORD}
      DOCUMENT_FEATURE_ENABLED: ${DOCUMENT_FEATURE_ENABLED}
      STORAGE_SERVICE_EXTERNAL_URL: ${STORAGE_SERVICE_EXTERNAL_URL}
      STORAGE_SERVICE_HOST: storage-service
      STORAGE_SERVICE_PORT: ${STORAGE_SERVICE_PORT}
      ORGANIZATION_PUBLIC_KEY: ${ORGANIZATION_PUBLIC_KEY}
      ORGANIZATION_PRIVATE_KEY: ${ORGANIZATION_PRIVATE_KEY}
      ENCRYPTION_PASSWORD: ${ENCRYPTION_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SIGNING_METHOD: ${SIGNING_METHOD}
      SWAGGER_BASEPATH: /test
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      ACCESS_CONTROL_ALLOW_ORIGIN: ${ACCESS_CONTROL_ALLOW_ORIGIN}
      LOG_LEVEL: ${API_LOG_LEVEL}
      - master-node
    ports:
      - ${API_PORT}:${API_PORT}
      #- "9230:9229"

  email-service:
    image: trubudget/email-notification:${TAG}
    command: ["npm", "start"]
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      EMAIL_PORT: ${EMAIL_PORT}
      AUTHENTICATION: ${AUTHENTICATION}
      LOG_LEVEL: ${EMAIL_LOG_LEVEL}
    depends_on:
      - emaildb
      - master-api
    ports:
      - "8890:8890"

  provisioning:
    image: trubudget/provisioning:${TAG}
    command: ["npm", "start"]
    environment:
      API_HOST: master-api
      API_PORT: ${API_PORT}
      ENVIRONMENT_TYPE: TEST
      #Other provisioning data:
      #ENVIRONMENT_TYPE: PROD
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
      LOG_LEVEL: ${PROVISIONING_LOG_LEVEL}
    depends_on:
      - master-api

  excel-export-service:
    image: trubudget/excel-export:${TAG}
    environment:
      PROD_API_HOST: master-api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: master-api
      TEST_API_PORT: ${API_PORT}
      PORT: ${EXPORT_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MODE: DEBUG
      LOG_LEVEL: ${EXCEL_LOG_LEVEL}
    ports:
      - "${EXPORT_PORT}:${EXPORT_PORT}"
     # - "9231:9229"
    depends_on:
      - master-api

  storage-service:
    image: trubudget/storage-service:${TAG}
    environment:
      PORT: ${STORAGE_SERVICE_PORT}
      ACCESS_CONTROL_ALLOW_ORIGIN: ${ACCESS_CONTROL_ALLOW_ORIGIN}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_HOST: minio
      MINIO_PORT: ${MINIO_PORT}
      LOG_LEVEL: ${STORAGE_LOG_LEVEL}
    depends_on:
      - minio
      - master-api
    ports:
      - "${STORAGE_SERVICE_PORT}:${STORAGE_SERVICE_PORT}"

  frontend:
    image: trubudget/frontend:${TAG}
    environment:
      NODE_ENV: ${NODE_ENV}
      REACT_APP_EXPORT_SERVICE_ENABLED: ${REACT_APP_EXPORT_SERVICE_ENABLED}
      REACT_APP_EMAIL_SERVICE_ENABLED: ${REACT_APP_EMAIL_SERVICE_ENABLED}
      PROD_API_HOST: master-api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: master-api
      TEST_API_PORT: ${API_PORT}
      EXPORT_HOST: ${EXPORT_HOST}
      EXPORT_PORT: ${EXPORT_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EXPORT_PORT: ${EXPORT_PORT}
      EXPORT_HOST: ${EXPORT_HOST}
      INLINE_RUNTIME_CHUNK: ${INLINE_RUNTIME_CHUNK}
    depends_on:
      - master-api
    ports:
      - "3000:80" # map nginx port 80 to localhost:3000

  # slave-node:
  #   # image: trubudget/blockchain:latest
  #   image: trubudget/blockchain:${TAG}
  #   environment:
  #     RPC_PORT: ${RPC_PORT}
  #     RPC_PASSWORD: ${RPC_PASSWORD}
  #     ORGANIZATION: ${ORGANIZATION}
  #     P2P_HOST: master-node
  #     P2P_PORT: 7447
  #     API_PROTO: http
  #     API_HOST: master-api
  #     API_PORT: ${API_PORT}
  #     EXTERNAL_IP: master-node
  #   depends_on:
  #     - master-node
  #   links:
  #     - master-node
  #     - master-api
  #   ports:
  #     - "7448:7447" # SLAVE_P2P_PORT
