version: "3"
services:
  master-node:
    build: ../../blockchain
    environment:
      RPC_HOST: master-node
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
    volumes:
      - /tmp/bcMasterVolume:/root/.multichain
    ports:
      - ${RPC_PORT}:${RPC_PORT}
      - "8085:8085"
      - "7447:7447"

  master-api:
    build: ../../api
    environment:
      APP_NAME: Trubudget
      PORT: ${API_PORT}
      NODE_LOCATION_LAT: "30.11"
      NODE_LOCATION_LNG: "4.68"
      NODE_COUNTRY: Brasil
      NODE_DESCRIPTION: UmbrellaCorp
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      RPC_HOST: master-node
      RPC_PORT: ${RPC_PORT}
      ROOT_SECRET: ${ROOT_SECRET}
      RPC_PASSWORD: ${RPC_PASSWORD}
    command: ["npm", "run", "dev"]
    volumes:
      - "../../api/src:/home/node/src:delegated"
    ports:
      - ${API_PORT}:${API_PORT}
      - "9230:9229"
    depends_on:
      - master-node

  provisioning:
    build:
      context: ../../provisioning
    command: ["npm", "start"]
    environment:
      API_HOST: master-api
      API_PORT: ${API_PORT}
      ENVIRONMENT_TYPE: PROD
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
    volumes:
      - "../../provisioning/src:/usr/src/app/src:delegated"
    depends_on:
      - master-api

  excel-export-service:
    build: ../../excel-export-service
    environment:
      PROD_API_HOST: master-api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: master-api
      TEST_API_PORT: ${API_PORT}
      PORT: 8888
    command: ["npm", "run", "dev"]
    volumes:
      - "../../excel-export-service/src:/home/node/src:delegated"
    ports:
      - "8888:8888"
      - "9231:9229"
    depends_on:
      - master-api

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.dev
      args:
        API_HOST: master-api
        API_PORT: ${API_PORT}
    environment:
      PORT: 3000
      NODE_ENV: ${NODE_ENV}
      CHOKIDAR_USEPOLLING: "true" # for hot reloading of source files
      REACT_APP_VERSION: ${REACT_APP_VERSION}
      REACT_APP_EXPORT_SERVICE_ENABLED: "true"
    volumes:
      - "../../frontend/src:/app/src"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - master-api
      - excel-export-service
    stdin_open: true
