version: "3"
services:
  master-node:
    build: ../../blockchain
    environment:
      RPC_HOST: master-node
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
    volumes:
      - /masterVolume:/root/.multichain
    ports:
      - ${RPC_PORT}:${RPC_PORT}
      - "8085:8085"
      - "7447:7447"

  master-api:
    build: ../../api
    environment:
      APP_NAME: Trubudget
      PORT: ${API_PORT}
      NODE_LOCATION_LAT: "30.11"
      NODE_LOCATION_LNG: "4.68"
      NODE_COUNTRY: Brasil
      NODE_DESCRIPTION: UmbrellaCorp
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      RPC_HOST: master-node
      RPC_PORT: ${RPC_PORT}
      ROOT_SECRET: ${ROOT_SECRET}
      RPC_PASSWORD: ${RPC_PASSWORD}
    command: ["npm", "run", "dev"]
    volumes:
      - "../../api/src:/home/node/src:delegated"
    ports:
      - ${API_PORT}:${API_PORT}
      - "9230:9229"
    depends_on:
      - master-node

  provisioning:
    build:
      context: ../../provisioning
    command: ["npm", "start"]
    environment:
      API_HOST: master-api
      API_PORT: ${API_PORT}
      ENVIRONMENT_TYPE: PROD
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
    depends_on:
      - master-api
