apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "frontend.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    project: "TruBudget"
    prometheus-monitoring: {{ .Values.service.monitoring}}
spec:
  type: {{ default "LoadBalancer" .Values.service.type }}
  ports:
    {{- if eq .Values.service.type "NodePort" }}
    - port: {{ .Values.frontend.ingressPort }}
      nodePort: {{ .Values.frontend.ingressPort }}
    {{- else }}
    - port: {{ .Values.frontend.port }}
    {{- end }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "frontend.name" . }}
    release: {{ .Release.Name }}
