version: "3"
services:
  blockchain-master:
    build:
      context: ../blockchain
    environment:
      RPC_PORT: ${RPC_PORT}
      ORGANIZATION: ${ORGANIZATION}
      RPC_PASSWORD: ${RPC_PASSWORD}
    ports:
      - "8000:8000"
      - "8085:8085"
