swagger: '2.0'
info:
  title: TruBudget
  version: v1
host: none
schemes:
  - https
securityDefinitions:
  Bearer:
    description: Send a JWT is required for all routes, except `session.authenticate`, of course.
    type: apiKey
    in: header
    name: Authorization
paths:
  "/user.create":
    post:
      operationId: "user.create"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            type: object
            required:
              - apiVersion
              - data
            properties:
              apiVersion:
                type: string
                enum:
                  - '1.0'
              data:
                type: object
                required:
                  - id
                  - displayName
                  - organization
                  - password
                properties:
                  id:
                    type: string
                  displayName:
                    type: string
                  organization:
                    type: string
                  password:
                    type: string
            example:
              apiVersion: '1.0'
              data:
                id: bob
                displayName: Bob the Builder
                organization: BuilderLand
                password: topsecret
      responses:
        '200':
          description: ''
          schema:
            type: string
            example:
              "alice"

  "/user.list":
    get:
      operationId: "user.list"
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
            required:
              - apiVersion
              - data
            properties:
              apiVersion:
                type: string
                enum:
                  - '1.0'
              data:
                type: object
                required:
                  - items
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      required:
                        - id
                        - displayName
                        - organization
                      properties:
                        id:
                          type: string
                        displayName:
                          type: string
                        organization:
                          type: string
            example:
              apiVersion: '1.0'
              data:
                items:
                  - id: bob
                    displayName: Bob the Builder
                    organization: BuilderLand
